# fly.toml app configuration file generated for fellowship-ey7nnq on 2025-06-30T17:29:24Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fellowship-ey7nnq'
primary_region = 'bom'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
